#ifndef PROJECT_PN_MIKROSKOP_ESP32_PN_CONFIG_H
#define PROJECT_PN_MIKROSKOP_ESP32_PN_CONFIG_H

#define DEBUG 1

// WIFI //
#define PN_CONFIG_WIFI_SSID "ssid"
#define PN_CONFIG_WIFI_PASS "password"
#define PN_CONFIG_WIFI_AUTH WIFI_AUTH_WPA2_PSK
#define PN_CONFIG_WIFI_ADDR "192.168.0.100" //Client IP
#define PN_CONFIG_WIFI_PORT 12345

#endif // PROJECT_PN_MIKROSKOP_ESP32_PN_CONFIG_H
